name: Deploy Documents to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TARGET_REPO_PAT }}
          publish_dir: doc-archive
          destination_dir: ''
